### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by Trivernis** [Trivernis/minecraft-data-rs#2]
The documentation is lacking usage examples. Those should be included in the README and in the lib.rs file to be displayed on docs.rs.
The README should also link to the crates.io and docs.rs page to make it easier to jump directly to the api documentation.

**Comment by BGR360** [comment]
I can take a pass at adding the field descriptions from the schema.json files as doc comments on the struct fields.

Side note: in theory, this entire crate could be generated by reading the schema.json files.

**Comment by Trivernis** [comment]
Yeah, the only reason I wrote the types manually was because I couldn't find a good tool to generate it from the schema at that time. Do you have any suggestions?

**Comment by BGR360** [comment]
Have you ever implemented a procedural macro before? I think the `syn` and `quote` crates should do the trick for generating Rust code. Then pipe it through rustfmt.

I don't want to promise anything, but I coulud probably help out with that.

**Comment by Trivernis** [comment]
> Have you ever implemented a procedural macro before? I think the `syn` and `quote` crates should do the trick for generating Rust code. Then pipe it through rustfmt.
> 
> I don't want to promise anything, but I coulud probably help out with that.

I think the schemafy crate is already doing that. The problem with proc macros is that those still cannot be interpreted by the Jetbrains rust plugin. If possible I'd prefer using a tool that generates the rust files with types for me instead tho there doesn't seem to be one that isn't hard to set up.

**Comment by BGR360** [comment]
> If possible I'd prefer using a tool that generates the rust files with types for me instead

Yes this is what I had in mind too. `syn` doesn't have to be used for proc macros only, you can just generate Rust source and save it to files.

> I think the schemafy crate is already doing that.

Neat. Do the `minecraft-data` schema files conform to "[JSON schema (draft 4)](http://json-schema.org/)"?

Also, sorry I never got around to putting comments on those types. Probably shouldn't have suggested I'd do that when I was working so much on my other project.

**Comment by Trivernis** [comment]
I'm busy with other projects myself but I'll look into code generation using syn when I need to parse data which hasn't type definitions yet

**Comment by Trivernis** [comment]
> Neat. Do the minecraft-data schema files conform to "[JSON schema (draft 4)](http://json-schema.org/)"?

Looking at it it actually doesn't seem that way. Looks like [ProtoDef](https://protodef.io/) and now thinking about it it makes perfect sense. 
The schemafy proc macro didn't panic but it generates nothing.

**Comment by minerj101** [comment]
The thing is there are only a few different rust protodef related codebases I have found so far on my extensive search.
https://github.com/roblabla/rust-protodef/blob/master/protocol.json
https://github.com/ProtoDef-io/protodefc
https://github.com/pollend/rogl/blob/3689c9f9d5691838880decde93e0ad1b028e6c3d/generator/src/command_parser.rs
https://crates.io/crates/protodef-parser

An effort should be put towards this at some point it seems...
