### ISSUE TITLE
Protocol support

### ISSUE THREAD

**Issue by wojtess** [Trivernis/minecraft-data-rs#4]
Is there adding in plan a support for protocol?

**Comment by Trivernis** [comment]
[This](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.9/protocol.json) information?

**Comment by wojtess** [comment]
> [This](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.9/protocol.json) information?

Yes

**Comment by rileysu** [comment]
I've been looking into this myself. The protocol spec is a bit strange not sure how this would best be implemented.
