### ISSUE TITLE
Issues with blocks before 1.13

### ISSUE THREAD

**Issue by nathanruiz** [Trivernis/minecraft-data-rs#7]
I've been having issues loading versions before 1.13. It seems to be failing due to the structure change for the `drops` field.

Before 1.13 with metadata:
```json
"drops": [
  {
    "drop": {
      "id": 3,
      "metadata": 0
    }
  }
]
```
Before 1.13 without metadata:
```json
"drops": [
  {
    "drop": 348,
    "minCount": 2,
    "maxCount": 4
  }
]
```
After 1.13:
```json
"drops": [
  8
]
```

I've been looking into a fix, but I'm unsure about the desired behavior. I can switch this field to an enum that supports the old version and the new, but that will break the current interface.

The other option is to extract the `id` from each object in `drops`, and put that into the `drops` array in the current structure. The downside with this approach is the user won't have access to the `metadata`, `minCount`, or `maxCount` fields.

**Comment by Trivernis** [comment]
According to the json schema, both formats are correct. So I'd suggest we change the type to be an enum with some functions to access data provided by both variants and release that as a new major version.

**Comment by nathanruiz** [comment]
We may want to merge this PR in at the same time as #9 since they are both breaking changes.
